version: '3.8'

services:
  # Development server
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "corepack enable && corepack prepare pnpm@8.15.0 --activate && pnpm install && pnpm dev --host"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  # Production build preview
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

